"""empty message

Revision ID: 402fec6d6c8b
Revises: 9e994c37bced
Create Date: 2020-06-29 20:34:33.249468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '402fec6d6c8b'
down_revision = '9e994c37bced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('website_link', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website_link')
    op.drop_column('Artist', 'website_link')
    # ### end Alembic commands ###
