"""empty message

Revision ID: 82522f69a7b7
Revises: e1eab5f18454
Create Date: 2020-07-04 17:24:40.516522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82522f69a7b7'
down_revision = 'e1eab5f18454'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Show', 'start_time',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Show', 'start_time',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
